from django.utils.translation import gettext_lazy as _

RESOURCES_TYPE_PRODUCTS = "PRODUCTS"
RESOURCES_TYPE_COSTUMERS = "CUSTOMERS"
RESOURCES_TYPE_ORDERS = "ORDERS"
RESOURCES_TYPE_CARTS = "CARTS"
RESOURCES_TYPE_CATEGORIES = 'CATEGORIES'
RESOURCES_TYPE_TAGS = 'TAGS'

STATUS_NOT_CREATED = "NOT_CREATED"
STATUS_CREATED = "CREATED"

RESOURCES_LIMIT_ITEMS = 100
RESOURCES_SLEEP = 0.4
