from django.utils.translation import gettext_lazy as _

RESOURCES_TYPE_PRODUCTS = "PRODUCTS"
RESOURCES_TYPE_COSTUMERS = "COSTUMERS"
RESOURCES_TYPE_ORDERS = "ORDERS"
RESOURCES_TYPE_CARDS = "CARDS"

STATUS_NOT_CREATED = "NOT_CREATED"
STATUS_CREATED = "CREATED"
STATUS_CHOICES = [
    (STATUS_NOT_CREATED, _("Not created")),
    (STATUS_CREATED, _("created")),
]

RESOURCES_LIMIT_ITEMS = 100
RESOURCES_SLEEP = 0.4
